/* Modelagem Básica de cliente
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE

NOME - CARACTERES(30)
CPF - NUMERICO(11)
EMAIL - CARACTERES(30)
TELEFONE - CARACTERES(30)
ENDERECO - CARACTERES(100)
SEXO - CARACTERES(1)

/* PROCESSO  DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLOS;

CREATE DATABASE PROJETO;

SHOW DATABASES;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA CLIENTE  */
/* TUNNING, DEIXAR O BANCO MAIS PERFORMATICO, COMEÇANDO PELO TIPO DE DADO */

CREATE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1), 
    EMAIL VARCHAR(30),
    CPF INT(11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);

/* VERIFICANDO TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* TIPAGEM, COMPARANDO CHAR E VARCHAR (TUNING) */

CARACTERES LITERAIS - CHAR E VARCHAR
NUMEROS - INT E FLOAT
FOTOS, DOCS - BLOB
TEXTOS - TEXT

1 CARACTERES = 1 BYTE

VARCHAR - VARIANTE, DINAMICA

CHAR(10) - 10 BYTES
|J|O|Ã|O|||||||

VARCHAR(10) - 4 BYTES
|J|O|Ã|O|||||||

/* CHAR MAIS PERFORMATICO POIS NÃO GASTA TEMPO MUDANDO DE TAMANHO */

/* NUM ENUM(MYSQL) = ENUMERAÇÃO */

FLOAT(TOTAL,VIRGULA) - REAIS 00.0
FLOAT(10,2)

INT - INTEIROS (11 DIGITOS)

REGISTRO/TUPLA - LINHA DE DADOS
CELULA - CAMPO

/* sintaxe basica de inserção - INSERT INTO TABELA... */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES ('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES ('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS (MAIS SEGURO)*/

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES ('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						  
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES ('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES ('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);
/* INT TEM UM RANGE */

/* COMANDO SELECT 
Seleção projeção e junção */

SELECT NOW() AS DATA_HORA, 'JOÃO VITOR' AS EU;

SELECT 'JOÃO VITOR';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/*TABELA ERRADA - NAO DIGITE DIRETAMENTE NO BANCO */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30)
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),

);

SELECT * FROM CLIENTE;